sonar.projectKey=PardosOrganization_PardosReservatios
sonar.organization=pardosorganization

# Código de aplicación a analizar (los 2 frontends)
sonar.sources=apps/landing-page/src,apps/reservation-system/src

# Excluir dependencias y artefactos de build
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**

sonar.sourceEncoding=UTF-8
