sonar.organization=pardosorganization
sonar.projectKey=PardosOrganization_PardosReservatios
sonar.projectName=PardosReservatios

sonar.sources=IAC,ansible,apps
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.module.css,**/.terraform/**,**/results.xml,failures_raw.txt,**/package-lock.json