sonar.organization=pardosorganization
sonar.projectKey=PardosOrganization_PardosReservatios
sonar.projectName=PardosReservatios

# Que analizar
sonar.sources=IAC,ansible,apps
sonar.sourceEncoding=UTF-8

# Exclusiones (artefactos, dependencias, generados y ruido)
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.module.css,**/.terraform/**,**/results.xml,failures_raw.txt,**/package-lock.json
