---
db_host: dev-database.cluster-xxx.us-east-1.rds.amazonaws.com
db_user: pardos_user
db_pass: "{{ lookup('env', 'DB_PASSWORD') | default('pardos_pass', true) }}"
db_name: pardos
redis_host: dev-redis.xxx.us-east-1.cache.amazonaws.com
db_proxy_endpoint: "pardos-dev-proxy.proxy-ckrkq6gkiir4.us-east-1.rds.amazonaws.com"
db_credentials_arn: "arn:aws:secretsmanager:us-east-1:181777503681:secret:pardos-dev/rds-credentials-pHyJoa"
