export const ROLE_PERMISSIONS = {
  admin: {
    label: 'Líder del Restaurante',
    color: '#e8453c',
    // Gestión general
    canManageUsers: true,
    canManageReservations: true,
    canViewReports: true,
    canManageClients: true,
    canManageTables: true,
    canViewAllReservations: true,
    canCancelAnyReservation: true,
    canConfigureSystem: true,
    canViewIncomesChart: true,
    canViewAdminDashboard: true,
    canManageAllUsers: true,
    canExportData: true,
    // Caja
    canViewCash: true,
    canManageCash: true,
    // Cocina
    canViewKitchen: true,
    canManageKitchenOrders: true,
    // Acciones exclusivas del admin
    canDeleteClients: true,
    canDeleteReservations: true,
    canSeatGuests: true,
    // Gestión del menú (solo admin/líder)
    canManageMenu: true,
  },

  cajero: {
    label: 'Cajero/a',
    color: '#e67e22',
    canManageUsers: false,
    canManageReservations: true,
    canViewReports: false,
    canManageClients: true,
    canManageTables: false,
    canViewAllReservations: true,
    canCancelAnyReservation: true,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: true,
    canManageCash: true,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
  },
  hostess: {
    label: 'Anfitriona de Bienvenida',
    color: '#8e44ad',
    canManageUsers: false,
    canManageReservations: true,
    canViewReports: false,
    canManageClients: true,
    canManageTables: true,
    canViewAllReservations: true,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: true,
  },
  mozo: {
    label: 'Mozo/a',
    color: '#27ae60',
    canManageUsers: false,
    canManageReservations: false,
    canViewReports: false,
    canManageClients: false,
    canManageTables: false,
    canViewAllReservations: false,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
  },
  jefe_cocina: {
    label: 'Jefe de Cocina',
    color: '#e67e22',
    canManageUsers: false,
    canManageReservations: false,
    canViewReports: false,
    canManageClients: false,
    canManageTables: false,
    canViewAllReservations: true,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canViewKitchen: true,
    canManageKitchenOrders: true,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
  },
}
